language: node_js

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - valgrind

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm t && npm run valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm t; fi

node_js:
  - 8
  - 10

cache:
  directories:
    - "node_modules"
